version: '2.1'

services:
  server:
    build:
      context: .
    working_dir: /src/
    command: mkdocs serve --dev-addr 0.0.0.0:8000 --livereload
    ports:
      - 8000:8000
    volumes:
      - ./:/src
      - ./extensions:/extensions