module.exports = {
  someSidebar: {
    "Hello World": ["root"],
    JavaScript: [
      "javascript/case-sensitive-paths-error",
      "javascript/change-query-params",
      "javascript/child-process-log-stream",
      "javascript/decipher-mdx-js",
      "javascript/dynamic-import",
      "javascript/dynamic-load-css",
      "javascript/get-collect-domain-name",
      "javascript/higher-order-function-tips",
      "javascript/introduction-code-dependency",
      "javascript/makeup-code-for-create-element",
      "javascript/mobx-minify-warning",
      "javascript/react-invalid-hook-call",
      "javascript/read-ctime",
      "javascript/request-library-description-for-json-value",
      "javascript/require-resolve",
      "javascript/treat-local-filesystem-methods",
      "javascript/use-lighthouse-through-authentication-for-programatically",
      "javascript/using-cypress-after-authentication",
      "javascript/vizjs-with-react",
      "javascript/wait",
      "javascript/yarn-add-slow",
      "javascript/yarn-offline-install",
    ],
    Docker: [
      "docker/command",
      "docker/pycharm",
      "docker/registry-api",
      "docker/swarm",
    ],
    Kubernetes: [
      "kubernetes/cron-wake-up-down",
      "kubernetes/error-helm-incompatible-version",
      "kubernetes/nginx-access-control-for-kubernetes",
      "kubernetes/shortcut-for-kubectl",
    ],
    MongoDB: ["mongodb/basic-query", "mongodb/basic-read-write"],
    MySQL: ["mysql/character-code"],
    Infrastructure: [
      "infrastructure/how-to-use-inlets",
      "infrastructure/multiple-reverse-proxy-sapmle-with-oauth2_proxy",
    ],
    Adobe: ["adobe/premire-pro"],
    Event: ["event/2018-05-21-cloud-native", "event/2018-10-13-abema-tv"],
    Jobs: ["jobs/ja"],
    Profile: [
      "profile/github-activity",
      "profile/index",
      "profile/skill",
      "profile/study-history",
    ],
    Python: [
      "python/django/celery-periodic-tasks",
      "python/django/fixture",
      "python/django/initialize-new-app",
      "python/django/introduction-of-celery-django",
      "python/django/seperate-django-database",
      "python/django/show-many-to-many-admin-view",
      "python/django/signal",
      "python/django/static-file",
      "python/django/unix-socket-and-nginx",
      "python/django/validate-only-alphabet",
      "python/flask/hello-flask-streamming-content",
      "python/flask/release-v1.0-check",
      "python/jupyter/change-jupyter-config-dir",
      "python/make-package",
      "python/pandas/pandas-convert-column-to-datetime",
      "python/see-falks-pytest",
    ],
    Raspberrypi: ["raspberrypi/os-install", "raspberrypi/purchace"],
    Tools: [
      "tools/alfread",
      "tools/cookiecutter",
      "tools/find-and-count-up-extensions",
      "tools/fish-history",
      "tools/git-hub-release",
      "tools/git-shortcut",
      "tools/git-version-match",
    ],
    WebAssembly: ["web-assembly/install-emcc"],
    Rust: ["rust/hello-world"],
  },
};
